### ISSUE TITLE
Network Manager

### ISSUE THREAD

**Issue by pdouglass** [fairdk/fair-ubuntu-centre#2]
In 02-network.sh we remove the default (gnome) network manager, and go with a static configuration.  This could be a liability because it makes it more difficult to change the servers network interfaces in the field.  

Specifically, how would a USB-3G-dongle connected to the server be configured without a network manager.  This, of course begs the question of how the mobile network interface would be configured with the network manager, but my assumption is that configuring an upling interface would be much smoother with the network manager, compared to editing /etc/network/interfaces.

**Comment by benjaoming** [comment]
This has been fixed and has been working fine for a while :) :+1: 

So it will just show the default eth0 interface as "not managed".
