### ISSUE TITLE
Install development packages for syllabus languages

### ISSUE THREAD

**Issue by benjaoming** [fairdk/fair-ubuntu-centre#26]
Now part of the Form 3 and Form 4 syllabus in Malawi:

Fortran, C, C++, Java, Pascal, COBOL

Visual Basic if possible... through WINE or Mono

**Comment by benjaoming** [comment]
## GFortran (for Fortran 95)

This is very easily solved by adding the `gfortran` package.

See: https://en.wikipedia.org/wiki/GNU_Fortran

## Java

The perhaps easiest IDE for Java is Netbeans -- but I have no idea how to find a resource for a secondary school kid for Java, it's so bloated :/

## C and C++

It's difficult, let's include `gcc`, but have to come up with some resource that introduces how to use an editor and a command line for compiling and running a program.

Netbeans for Java is also useful, see: https://tutorialforlinux.com/2015/01/04/netbeans-8-x-ide-for-cc-quick-start-with-hello-world-project-example-easy-visual-guide/

## Pascal
`lazarus` is an IDE for Free Pascal, running on Ubuntu.

 * http://www.schoolfreeware.com/Free_Pascal_Tutorials.html
 * https://www.lazarus-ide.org/

## COBOL

`gnu-cobol` is the package, again should write a guide introducing how to write and compile a program. Compiler command is `cobc`
See: https://askubuntu.com/questions/287180/how-to-compile-and-run-a-cobol-program

**Comment by fairdklab** [comment]
On Sat, 21 Apr 2018, 17:39 Benjamin Bach, <notifications@github.com> wrote:

> GFortran (for Fortran 95)
>
> This is very easily solved by adding the gfortran package.
>
> See: https://en.wikipedia.org/wiki/GNU_Fortran
> Java
>
> The perhaps easiest IDE for Java is Netbeans -- but I have no idea how to
> find a resource for a secondary school kid for Java, it's so bloated :/
>

BlueJ might be a good IDE for teaching. It was used at the university of
Ghent in the past.
